bands/urls.py
from django.urls import path

from bands import views

urlpatterns = [
    path("musician/<int:musician_id>/", views.musician, name="musician"),
    path("musicians/", views.musicians, name="musicians"),
    path("bands/", views.bands, name="bands"),
    path("bands/<int:band_id>/", views.band, name="band"),
    path("venues/", views.venues, name="venues"),
]

riff_mates/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("credits/", home_views.credits),
    path("about/", home_views.about),
    path("version/", home_views.version),
    path("news/", home_views.news_advanced, name="news"),
    path("bands/", include("bands.urls")),
]

bands/models.py
from django.db import models


class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, db_index=True)
    birth = models.DateField()

    class Meta:
        indexes = [models.Index(fields=['last_name', 'first_name'])]

    def __str__(self):
        return f"Musician(id={self.id}, last_name={self.last_name})"


class Venue(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"Venue(id={self.id}, name={self.name})"


class Room(models.Model):
    name = models.CharField(max_length=50)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

    def __str__(self):
        return f"Room(id={self.id}, name={self.name})"

    class Meta:
        unique_together = (("name", "venue"),)


class Band(models.Model):
    name = models.CharField(max_length=50)
    musicians = models.ManyToManyField(Musician)

    def __str__(self):
        return f"Band(id={self.id}, name={self.name})"

home/models.py
from django.db import models

# Create your models here.

bands/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from bands.models import Musician, Band, Venue, Room

DEFAULT_PAGE_NUMBER = 1
DEFAULT_PAGE_SIZE = 2
MAX_PAGE_SIZE = 100


def musician(request, musician_id):
    musician = get_object_or_404(Musician, id=musician_id)
    data = {"musician": musician}
    return render(request, "musician.html", data)


def musicians(request):
    all_musicians = Musician.objects.all().order_by("last_name", "first_name")

    page_num = request.GET.get("page", DEFAULT_PAGE_NUMBER)
    page_num = int(page_num)
    page_size = request.GET.get("size", DEFAULT_PAGE_SIZE)
    page_size = int(page_size)

    paginator = Paginator(all_musicians, page_size)

    if page_num < 1:
        page_num = 1
    elif page_num > paginator.num_pages:
        page_num = paginator.num_pages

    if page_size < 2:
        page_size = 1
    elif page_size > MAX_PAGE_SIZE:
        page_size = MAX_PAGE_SIZE

    page = paginator.page(page_num)
    data = {
        "musicians": page.object_list,
        "page": page,
        "page_size": page_size,
    }

    return render(request, "musicians.html", data)


def bands(request):
    all_bands = Band.objects.all().order_by("name")
    data = {"bands": all_bands}
    return render(request, "bands.html", data)


def band(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    data = {"band": band}
    return render(request, "band.html", data)


def venues(request):
    all_venues = Venue.objects.all().order_by("name")
    data = {"venues": all_venues}
    return render(request, "venues.html", data)

home/views.py
from datetime import date
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse


def credits(request):
    content = "Nicky\nMarc"

    return HttpResponse(content, content_type="text/plain")


def about(request):
    content = "<html><body><p>hello</p></body></html>"

    return HttpResponse(content)


def version(request):
    content = {
        "version": "1.0.0",
    }

    return JsonResponse(content, json_dumps_params={"indent": 4})


def news(request):
    data = {
        "news": [
            "RiffMates now has a news page!",
            "RiffMates has its first web page",
        ],
    }

    return render(request, "news2.html", data)


def news_advanced(request):
    data = {
        "news": [
            (date(2017, 3, 12), "RiffMates now has a news page!"),
            (date(2024, 6, 1), "RiffMates has its first web page"),
        ],
    }

    return render(request, "news_advanced.html", data)

templates/band.html
{% extends "base.html" %}

{% block title %}
    {{block.super}}: Band Details
{% endblock title %}

{% block content %}
    <h1>
        {{ band.name }}
    </h1>

    <ul>
        {% for musician in band.musicians.all %}
            <li>
                {{ musician.last_name }}, {{ musician.first_name }}
            </li>
        {% empty %}
            <li>
                No musicians in this band
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/bands.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }}: Band Listing
{% endblock %}

{% block content %}
    <h1>Bands</h1>

    <ul>
        {% for band in bands %}
            <li>
                <a href="{% url "band" band.id %}">
                    {{ band.name }}
                </a>
            </li>
        {% empty %}
            <li>
                <i>No bands in the database</i>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>
        {% block title %}RiffMates{% endblock %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/experimental.html
I love the sound a {{ instrument }} makes.
A shiny {{ instrument | safe }} is good.

{% autoescape off %}
Don't put a {{ instrument }} too close to your ear.
{% endautoescape %}

templates/musician.html
{% extends "base.html" %}

{% block title %}
    {{block.super}}: Musician Details
{% endblock title %}

{% block content %}
    <h1>
        {{ musician.first_name }} {{ musician.last_name }}
    </h1>

    <p>
        Was born {{ musician.birth }}.
    </p>
{% endblock content %}

templates/musicians.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }}: Musician Listing
{% endblock %}

{% block content %}
    <h1>Musicians</h1>

    <ul>
        {% for musician in musicians %}
            <li>
                <a href="{% url "musician" musician.id %}">
                    {{ musician.last_name }}, {{ musician.first_name }}
                </a>
            </li>
        {% empty %}
            <li>
                <i>No musicians in the database</i>
            </li>
        {% endfor %}
    </ul>

    {% if page.has_other_pages %}
        {% if page.has_previous %}
            <a href="{% url 'musicians' %}?page={{ page.previous_page_number }}&size={{ page_size }}"
            >Prev</a> &nbsp;&nbsp;&nbsp;
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'musicians' %}?page={{ page.next_page_number }}&size={{ page_size }}"
            >Next</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/news.html
<!doctype html>
<html lang="en">
<head>
    <title>RiffMates News</title>
</head>
<body>
    <h1>RiffMates News</h1>

    <ul>
        {% for item in news %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/news2.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }}: News
{% endblock %}

{% block content %}
    <h1>RiffMates News</h1>

    <ul>
        {% for item in news %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/news_advanced.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }}: News
{% endblock %}

{% block content %}
    <h1>RiffMates News</h1>

    <ul>
        {% for item in news %}
            <li class="{% cycle 'odd' 'even' %}">
                {{ item.0|date:'Y/m/d' }}: {{ item.1 }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/venues.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }}: Venue Listing
{% endblock %}

{% block content %}
    <h1>Venues</h1>

    <ul>
        {% for venue in venues %}
            <li>
                {{ venue.name }}
                <ul>
                    {% for room in venue.room_set.all %}
                        <li>
                            {{ room.name }}
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% empty %}
            <li>
                <i>No Venues in the database</i>
            </li>
        {% endfor %}
    </ul>
{% endblock %}